export const students = [
    {
        id: 1,
        name: "John Doe",
        age: 16,
        grade: "10th Grade",
        email: "john.doe@example.com",
    },
    {
        id: 2,
        name: "Jane Smith",
        age: 17,
        grade: "11th Grade",
        email: "jane.smith@example.com",
    },
    {
        id: 3,
        name: "Samuel Johnson",
        age: 15,
        grade: "9th Grade",
        email: "samuel.johnson@example.com",
    },
    {
        id: 4,
        name: "Emily Davis",
        age: 18,
        grade: "12th Grade",
        email: "emily.davis@example.com",
    },
    {
        id: 5,
        name: "Michael Brown",
        age: 16,
        grade: "10th Grade",
        email: "michael.brown@example.com",
    },
    {
        id: 6,
        name: "Sophia Wilson",
        age: 14,
        grade: "8th Grade",
        email: "sophia.wilson@example.com",
    },
    {
        id: 7,
        name: "Daniel Moore",
        age: 17,
        grade: "11th Grade",
        email: "daniel.moore@example.com",
    },
    {
        id: 8,
        name: "Isabella Taylor",
        age: 18,
        grade: "12th Grade",
        email: "isabella.taylor@example.com",
    },
    {
        id: 9,
        name: "Ethan Anderson",
        age: 15,
        grade: "9th Grade",
        email: "ethan.anderson@example.com",
    },
    {
        id: 10,
        name: "Olivia Martinez",
        age: 16,
        grade: "10th Grade",
        email: "olivia.martinez@example.com",
    },
];
